- service/client.go
- service/jobs_service.go
A couple of improvements/fixes to things I noticed while testing.
- Bumping the timeout for client requests as we are keeping the "start job" synchronous to simplify but this means it could take a while to return in case the docker image is missing and needs to be pulled. 
- Running the container in host mode in dev environments to help with testing (localhost becomes reachable from within the container).
> Improvements

- Makefile
Looks like the pipeline still needs to login into the docker registry to release on Github.
> Fix release step

- service/audit.go
- service/jobs_api.go
- service/jobs_service.go
- service/service.go
- service/store/bitcask.go
PR adds some logic to remove recording jobs upon successful exit. This doesn't affect the recording files since they are stored in a volume which is preserved and usually already deleted by `calls-recorder` once successfully published.
https://mattermost.atlassian.net/browse/MM-49189
> [MM-49189] Cleanup resources on successful job

- service/client.go
- service/jobs_api.go
- service/jobs_service.go
- service/service.go
PR decouples the existing logic to update the runner (docker image) so that it can be used independently from the API. This allows the plugin side to do this potentially time expensive operation asynchronously on activation rather than waiting for the first recording job to start. 
https://github.com/mattermost/mattermost-plugin-calls/pull/286
https://mattermost.atlassian.net/browse/MM-49267
> [MM-49267] Implement API endpoint to update job runner

- go.mod
- go.sum
- service/job.go
- service/job_test.go
- service/jobs_api.go
- service/utils.go
- service/utils_test.go
PR adds a check on the recorder runner (docker image) so that it matches the expected minimum version.
**Note**: these changes will break passing the image by hash. To fix this we need more logic since we likely need to fetch the image and check the tags to figure out the version. Given the need to merge this asap I'd like to defer this extra work to a future release and think this through with more calm.
https://mattermost.atlassian.net/browse/MM-49635
> [MM-49635] Add minimum supported version for recorder

- service/docker_security_opts.go
- service/jobs_service.go
PR basically includes a list of syscalls that need to be passed through [`seccomp` ](https://docs.docker.com/engine/security/seccomp/) when running the recording job to allow Chromium to run in a sandbox .
The list is coming from https://github.com/jessfraz/dotfiles/blob/master/etc/docker/seccomp/chrome.json, with only one addition being `clone3`, needed since some recent `glibc` changes (https://github.com/moby/moby/pull/42836 for context). 
https://github.com/mattermost/calls-recorder/pull/14
https://mattermost.atlassian.net/browse/MM-49667
> [MM-49667] Run recording job with security opts

- service/jobs_service.go
Allowing to override the docker network mode used by the job containers is necessary to make recordings work in the docker-in-docker setup we have in the e2e pipeline.
> Allow override of docker network mode

- Makefile
- service/docker_utils.go
- service/jobs_service.go
PR adds a connectivity check to the underlying job API (docker in this case) during initialization. This is an effort to fail fast if something is clearly broken since otherwise the first error would come when the plugin tries to connect or worse on recording attempt.
https://mattermost.atlassian.net/browse/MM-50706
> [MM-50706] Add connectivity check to API on service initialization

- service/jobs_service.go
Logging `ImagePull`'s output to improve visibility on what's actually going on while updating the recorder's image.
https://mattermost.atlassian.net/browse/MM-51323
> [MM-51323] Log ImagePull output

- service/client.go
- service/client_test.go
- service/version.go
- service/version_test.go
Implementing a client method to fetch version info to help the plugin side verify the service meets requirements.
https://github.com/mattermost/mattermost-plugin-calls/pull/423
https://mattermost.atlassian.net/browse/MM-52485
> [MM-52485] Expose version info

- service/client.go
- service/client_test.go
Returning a proper error in case of failed client auth. This helps to properly distinguish this case and act on it from the plugin side.
https://github.com/mattermost/mattermost-plugin-calls/pull/422
https://mattermost.atlassian.net/browse/MM-52382
> [MM-52382] Implement unauthorized client error

- service/jobs_service.go
- Working with @DHaussermann we found we couldn't start recordings because his docker was running the 6 MM containers, so offloader thought we were past the `MaxConcurrentJobs`. Fixing that. (There doesn't seem to be an easy way to encode the image in the container list request, the `ancestor` field didn't work for me (see: https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerList )).
- https://mattermost.atlassian.net/browse/MM-53083
> MM-53083 - Fix for: Container list contains all containers

- service/job.go
- service/job_test.go
Updating the min required version as we just released [recorder `v0.3.3`](https://hub.docker.com/layers/mattermost/calls-recorder/v0.3.3/images/sha256-e2cee54e57c8c87481089e1bf3a4d173aa7d3083c3b92a4e060e3ffeeb845047?context=explore).
Also updating the tests to ease the process going forward.
> Update minimum support recorder version

- service/kubernetes/service.go
- service/kubernetes/utils.go
We are adding similar logic on the k8s implementation side to limit running more than the configured maximum number of jobs, unless running in dev mode.
> Enforce MaxConcurrentJobs limit

- .github/workflows/ci.yml
When building the image on the protected `master` branch it gets a different name which was causing failures once we merged https://github.com/mattermost/calls-offloader/pull/34. We fix this by simply using the latest built image.
> Fix image name in k8s CI

- service/docker/service.go
There was an issue causing an erroneous timeout when starting a job that required the image to be fetched.
https://mattermost.atlassian.net/browse/MM-53922
> [MM-53922] Fix potential timeout error on first job creation

- public/job/job.go
- public/job/job_test.go
- service/auth.go
- service/auth/service.go
- service/client_test.go
To make the service play nicely with K8S (or with any other form of load balancing of multiple instances) we added some very hacky logic in https://github.com/mattermost/mattermost-plugin-calls/pull/479 to essentially re-attempt actions due to failed authentication. Not only was this pretty horrible code to implement but also it didn't work particularly well with round-robin load balancers which would distribute each request to a different backend, causing the client to just give up after reaching the maximum failed attempts.
To alleviate these issues and simplify the flow we are adding some functionality to automatically register a client (if missing) upon authentication attempt. This has the huge benefit of removing the need to make separate HTTP requests which could all hit different …
> [MM-54232] Implement automatic client registration

- go.mod
- go.sum
- public/job/job.go
- public/job/job_test.go
- service/kubernetes/utils_test.go
Need to bump `calls-recorder` related dependencies and minimum version before cutting `v0.3.2`.
> Bump recorder

- service/kubernetes/service.go
- service/kubernetes/utils.go
We are using a privileged [init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to set the necessary `sysctl` setting on the kubernetes node which is required by the calls recording process (to enable using the Chromium sandbox).
https://mattermost.atlassian.net/browse/MM-54411
> [MM-54411] Use init container to set necessary node level sysctl

- service/docker/service.go
- If we're in dev mode, we don't need to pull the published container.
- none
> Don't pull the published container if we're in dev mode

- config/config.sample.toml
- docs/kubernetes_development.md
- service/config.go
- service/config_test.go
- service/docker/service.go
- service/docker/service_test.go
- service/jobs_service.go
- service/kubernetes/service.go
PR implements a retention policy for failed jobs through the use of a new `failed_jobs_retention_time` config setting. So far we only deleted successful jobs to prevent data loss. However this has caused a bit of a pain in production as we had many failures which always required manual intervention.
Implementation wise this is trivial to do in the `kubernetes` case as there's a setting that does it automatically (`TTLSecondsAfterFinished`). For `docker` we implement a simple cronjob.
https://mattermost.atlassian.net/browse/MM-49202
> [MM-49202] Implement retention policy of failed jobs

- cmd/offloader/main.go
- service/config.go
- service/config_test.go
Forgot to test the other path (environment) which unfortunately suffered from the same limitation, unable to parse days as duration.
https://mattermost.atlassian.net/browse/MM-54925
> [MM-54925] Fix env override parsing for FailedJobsRetentionTime

- Makefile
- go.mod
- go.sum
- service/docker/service.go
Updating some dependencies to support the latest improvements.
https://github.com/mattermost/mattermost-plugin-calls/pull/565
> [MM-53432] Improvements

- docs/performance.md
Attaching the results of preliminary performance tests. I selected the same instance type we use in production for recordings `c6i.2xlarge` and executed on all the models we include (`tiny`, `base`, `small`) with a base sample of 10 minutes.
For the default configuration of threads (NumCPU / 2) I also performed tests on a full hour of meeting sample.
The call samples were extracted from real developers meetings so the test should be as close as possible to a real use case with the caveat that it was a single track. In general though I wouldn't expect multiple tracks to cause significant overhead since it's unlikely for speech from different tracks to be overlapping for long periods.
What's likely causing some overhead is the number of speech segments that we get out of these tracks (due …
> [MM-55475] Performance tests

- config/config.sample.toml
- public/job/job.go
- service/config.go
- service/config_test.go
- service/docker/service.go
- service/helper_test.go
- service/jobs_service.go
- service/kubernetes/service.go
We want to allow setting resource limits and requests for jobs we manage so that it's easier for Kubernetes to schedule them properly based on available nodes resources.
I kept the implementation simple to avoid redefining a bunch of K8S types. The downside is that we need to pass some potentially ugly JSON but the alternative seemed just a lot of repetition and potentially less powerful overall. 
This is how it would look like to define specific limits and requests for both jobs we support today from a helm chart:
```
- name: JOBS_KUBERNETES_JOBSRESOURCEREQUIREMENTS
value: "{\"transcribing\":{\"limits\":{\"cpu\":\"4000m\"},\"requests\":{\"cpu\":\"2000m\"}},\"recording\":{\"limits\":{\"cpu\":\"2000m\"},\"requests\":{\"cpu\":\"1000m\"}}}"
```
Again, thanks @gabrieljackson for the tip :) …
> [MM-56184] Allow passing Kubernetes resource requirements to jobs

- config/config.sample.toml
- public/job/job.go
- public/job/job_test.go
- service/config.go
- service/docker/service.go
- service/helper_test.go
- service/jobs_api.go
- service/jobs_service.go
- service/kubernetes/service.go
PR adds a new config setting to control the image registry to be used during validation of job runners coming from the plugin side. This is useful in case of air gapped environments that may not be able to fetch from the default (public) Mattermost docker registry but would like to use a local registry instead.
https://mattermost.atlassian.net/browse/MM-53555
> [MM-53555] Support defining image registry through configuration

- service/api/server.go
- service/api/server_test.go
A small usability improvement. We return an error in case the HTTP server fails to start immediately (up to a second). This can happen, for example, due to an invalid certificate provided (added a test for this case).
> Return error in case of failure to start HTTP server

- go.mod
- go.sum
- public/job/job.go
- public/job/job_test.go
- service/docker/service.go
- service/docker/service_test.go
- service/kubernetes/service.go
- service/kubernetes/utils.go
- service/kubernetes/utils_test.go
PR decouples this service from any job specific config. This assumes proper validation should be performed preferably on the client side (plugin).
https://github.com/mattermost/mattermost-plugin-calls/pull/667
https://mattermost.atlassian.net/browse/MM-57483
> [MM-57483] Decouple service from job specific configs

- docs/performance.md
- Performance benchmarking for live captions
- https://mattermost.atlassian.net/browse/MM-58014
> [MM-58014] Performance benchmarking for live captions

- .github/workflows/ci.yml
- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
- go.mod
Updating Golang runtime to v1.22. Also taking the chance to update the linter and the CI actions.
https://mattermost.atlassian.net/browse/MM-60187
> [MM-60187] Update Golang to v1.22

- config/config.sample.toml
- service/kubernetes/service.go
PR implements a new k8s specific config setting to allow passing a [`PersistentVolumeClaim`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims) to be used for storage of jobs data (e.g., recording files). 
This value can also be passed through the `JOBS_KUBERNETES_PERSISTENTVOLUMECLAIMNAME` environment variable.
https://mattermost.atlassian.net/browse/MM-56524
> [MM-56524] Allow using a PersistentVolumeClaim to store jobs data

- config/config.sample.toml
- service/kubernetes/service.go
- service/kubernetes/utils.go
- service/kubernetes/utils_test.go
PR removes the init container setting the [deprecated](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#linux-user-namespaces) `kernel.unprivileged_userns_clone=1` and adds a new `node_sysctls` config setting to let admins set custom sysctls that may be needed at the node level.
This new config is also controlled by the `JOBS_KUBERNETES_NODESYSCTLS` env var.
https://mattermost.atlassian.net/browse/MM-62189
> [MM-62189] Allow passing custom node level sysctls

- docs/getting_started.md
We were missing explicit guidelines on how to make this service work in a private network scenario, where connecting to the external SiteURL may not always work (e.g., because it's not reachable from within or to avoid the HTTPs complicacy and use a private URL instead).
Should also fix #65
> Add doc section on how to run in a private network

- go.mod
Bumping the Golang version used to build. 
https://mattermost.atlassian.net/browse/MM-63296
> [MM-63296] Bump Golang version to v1.23.6

- docs/getting_started.md
Adding a note to our docs on using `DOCKER_NETWORK=host` as it happened to be necessary for a customer running things in VMs.
> Add note on DOCKER_NETWORK use

- config/config.sample.toml
- service/docker/service.go
During initial deployment, checking logs from jobs can be helpful for debugging failures. However, since jobs that fail on startup are not retained, accessing their logs can be tricky since it requires careful timing with the `docker logs` command.
To simplify this, we introduce a new configuration setting that allows admins to direct job logs to the console.
/cc @sadohert 
https://mattermost.atlassian.net/browse/MM-64441
> [MM-64441] Add setting to control outputting job logs
